
name: 'Catu_aws_snow_dbt_project'
version: '1.0.0'
profile: 'Catu_aws_snow_dbt_project'
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  Catu_aws_snow_dbt_project:
    Bronze:
      +materialized: table
      +schema: Bronze
    Silver:
      +materialized: table
      +schema: Silver
    Gold:
      +materialized: table
      +schema: Gold  
      ephemeral:
        +materialized: ephemeral
        

